global:
 # интервал забора метрик
 scrape_interval: 15s
 # интервал вычисления выражений для алертов
 evaluation_interval: 15s

scrape_configs:
  - job_name: 'book-service'
    metrics_path: "/metrics"
    static_configs:
      - targets: ['handler:8080']

  - job_name: 'rabbitmq'
    static_configs:
      - targets: ['rabbitmq:15692']

alerting:
 alertmanagers:
    - static_configs:
        - targets:
            - "alertmanager:9093"

rule_files:
  - "alert_rules.yml"  # путь до файла с алертами