all: 
	docker compose up -d
in:
	docker exec -it keydb bash
#keydb-cli

#SET student:sp5:14 "popov viacheslav"
#HSET student:sp5:info name "popov viacheslav" age "20" email "machina@gmail.com"
#RPUSH student:sp5:timetable "math" "algo" "fizra"
#LRANGE student:sp5:timetable 0 -1
#SADD student5:skills "Docker" "Java" "Go"
#SMEMBERS student:sp5:skills 
#ZADD student:sp5:tasks_w_priority 100 "done 1lab" 150 "done 2lab"
#ZRANGE student:sp5:tasks_w_priority 0 -1
