version: '3.8'

services:
  rabbitmq:
    image: rabbitmq:management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest

  producer:
    build:
      context: .
      dockerfile: producer/Dockerfile
    depends_on:
      - rabbitmq

  consumer:
    build:
      context: .
      dockerfile: consumer/Dockerfile
    depends_on:
      - rabbitmq
